version: '3'

services:
  auction-service:
    container_name: auction
    build: ./AuctionController
    ports:
      - "8080:8080"
    expose:
      - 8080



  catalogue-service:
    container_name: catalogue
    build: ./CatalogueService
    ports:
      - "8082:8082"
    expose:
      - 8082

  payment:
    container_name: payment
    build: ./paymentService
    ports:
      - "8081:8080"
    expose:
      - 8081


  master:
    container_name: master
    build: ./MasterController
    ports:
      - "8083:8083"
    expose:
      - 8083


  frontend:
    container_name: frontend
    build: ./AuctionHub
    ports:
      - "8084:8080"
    expose:
      - 8084


  user:
    container_name: user
    build: ./UserService
    ports:
      - "8085:8080"
    expose:
      - 8085

  ubuntu:
    image: ubuntu
    command: bash -c "while true; do echo hello; sleep 2; done"